--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FrostCheat/Prefixes
build-by-default: true
branches:
- main
projects:
  Prefixes:
    path: ""
    icon: "icon.png"
    libs:
      - src: LatamPMDevs/Commando/Commando
        version: ^3.1.1
        branch: pm5
      - src: LatamPMDevs/ConfigUpdater/ConfigUpdater
        version: ^2.0.1
        branch: master
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: muqsit/InvMenu/InvMenu
        branch: "pm5"
        version: ^4.6
    lint: false
...
