---
name: Prefixes
version: 1.4.0
main: frostcheat\prefixes\Prefixes
author: FrostCheat
website: http://www.aquamcpe.xyz/
api: 5.3.0
description: Plugin to create chat prefixes for your users

softdepend:
  - RankSystem

permissions:
  prefixes.command:
    default: true
  prefixes.command.help:
    default: op
  prefixes.command.create:
    default: op
  prefixes.command.reload:
    default: op
  prefixes.command.set:
    default: op
  prefixes.command.remove:
    default: op
  prefixes.command.delete:
    default: op
  prefixes.command.save:
    default: op
  prefixes.command.setlanguage:
    default: op
...
