# Don't touch this setting it may break the entire plugin
config-version: 4

prefix-max-characters-name: 25
prefix-max-characters-format: 50

# Default language used
# Supported languages: en_us, es_es, fr_fr, gr_ge, pr_br, rs_rs
default-language: en_us

# If this option is "true" it means that you will use the RankSystem plugin to display the prefix.
# If this option is "false" it means that you will use the chat format of this Plugin.
# If you change the RankSystem placeholder you must restart the server
# Remember that for it to work in the RankSystem configuration it must be between {}, example {prefix}
rank-system-chat: false
rank-system-prefix-placeholder: "prefix"

# Chat Format of this plugin (rank-system-chat must be "false")
chat-format-prefix: "%prefix% &7%name%: &f%message%"
chat-format: "&7%name%: &f%message%"